apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-topic-gateway
  labels:
    app: {{ template "name" . }}
    component: topic-gateway
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.topicGateway.service.type }}
  ports:
    - port: {{ .Values.topicGateway.service.externalPort }}
      targetPort: {{ .Values.topicGateway.service.internalPort }}
      protocol: TCP
      name: {{ .Values.topicGateway.service.name }}
  selector:
    app: {{ template "name" . }}
    component: topic-gateway
    release: {{ .Release.Name }}
