apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-topic-controller
  labels:
    app: {{ template "name" . }}
    component: topic-controller
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: topic-controller
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-topic-controller
          image: "{{ .Values.topicController.image.repository }}:{{ .Values.topicController.image.tag }}"
          imagePullPolicy: {{ .Values.topicController.image.pullPolicy }}
          env:
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
            value: {{ template "fullname" . }}-kafka:9092
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
            value: {{ template "fullname" . }}-zookeeper:2181
